<?php
/**
 *  * Implements hook_block_info().
 *   */
function rnp_catalog_block_info() {
  $blocks['rnp_catalog'] = array(
    // The name that will appear in the block list.
    'info' => 'rnp_catalog',
    // Default setting.
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

function rnp_catalog_block_view() {
  $block = array();
  $block['content'] = theme('rnp_catalog-theme');
  return $block;
}

function rnp_catalog_theme($existing, $type, $theme, $path) {
  return array(
    'rnp_catalog-theme' => array(
      'template' => 'html-page'
    ),
  );
}

function rnp_catalog_menu() {
  $items = array();
  $items['books'] = array(
    'title'             =>  'Books View',  //page title
    'description'       =>  'Books Information',  //description show when mouse hover on link
    'page callback'     =>  'books_list',  //callback function which is invoked when menu item is called.
    'access callback'   =>  true,  //any user can access this page
  );
  return $items;
}

function rnp_catalog_help($path, $arg) {
  switch ($path) {
      case "admin/help#rnp_catalog":
        return t("Displays links to nodes created on this date");
        break;
    }
}
